USE BD_LEHKOVIE1;
GO
CREATE PROCEDURE DOGOVOR1_DOB 
@VIN_NUMBER_TRADE VARCHAR(50), 
@ID_CHELOVEK VARCHAR(50), 
@VIN_NUMBER VARCHAR(50),
@PRICE_DOP MONEY,
@PRICE MONEY,
@DATA_DOG DATE
AS
BEGIN
SET NOCOUNT ON;
INSERT INTO DOGOVOR( DATA_DOG, PRICE_DOP, PRICE,ID_CHELOVEK,VIN_NUMBER,VIN_NUMBER_TRADE)
VALUES (@DATA_DOG, @PRICE_DOP, @PRICE,@ID_CHELOVEK,@VIN_NUMBER,@VIN_NUMBER_TRADE)
END